openapi: 3.0.0
info:
  title: Gmail Agent Tools
  version: 1.0.1
servers:
  - url: https://gmail-agent.onrender.com

paths:
  /send_email:
    post:
      operationId: sendEmail
      summary: Send an email with optional attachment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailRequest'
      responses:
        '200':
          description: Email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                  status:
                    type: string

  /validate_email:
    post:
      operationId: validateEmail
      summary: Validate an email address (syntax + SMTP)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateEmailRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean

  /summarize_text:
    post:
      operationId: summarizeText
      summary: Summarize a given block of text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizeTextRequest'
      responses:
        '200':
          description: Summary result
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string

components:
  schemas:
    SendEmailRequest:
      type: object
      required: [to, subject, body]
      properties:
        to:
          type: string
          description: The recipient's email address
