openapi: 3.0.0
info:
  title: Gmail Tool
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /send_email:
    post:
      operationId: sendEmail
      summary: Send email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                subject:
                  type: string
                body:
                  type: string
                attachment_path:
                  type: string
      responses:
        '200':
          description: OK
