openapi: 3.0.0
info:
  title: Gmail Agent Tools
  version: 1.0.0
servers:
  - url: https://gmail-agent.onrender.com

paths:
  /send_email:
    post:
      operationId: sendEmail
      summary: Send an email with optional attachment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailRequest'
      responses:
        '200':
          description: Email sent successfully

  /validate_email:
    post:
      operationId: validateEmail
      summary: Validate an email address (syntax + SMTP)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateEmailRequest'
      responses:
        '200':
          description: Validation result

  /summarize_text:
    post:
      operationId: summarizeText
      summary: Summarize a given block of text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizeTextRequest'
      responses:
        '200':
          description: Summary result

components:
  schemas:
    SendEmailRequest:
      type: object
      required: [to, subject, body]
      properties:
        to:
          type: string
          description: The recipient's email address
        subject:
          type: string
          description: The subject line of the email
        body:
          type: string
          description: The content of the email
        attachment_path:
          type: string
          description: Optional path to a file to attach

    ValidateEmailRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          description: Email address to validate

    SummarizeTextRequest:
      type: object
      required: [text]
      properties:
        text:
          type: string
          description: Text to be summarized
